services:
  postgres:
    image: postgres:latest
    container_name: coupon_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coupon
    ports:
      - "5432:5432"